### ISSUE TITLE
normalDistributionStages in config file

### ISSUE THREAD

**Issue by vladSeeq** [grafana/jslib.k6.io#107]
Hey team, 
I'm trying to use normalDistributionStages in the config file but seems like this is not supported functionality, or I'm doing something wrong...
There is my code:
{
  "stages": [{
    "normalDistributionStages": "(10, 20, 5)"
  }]
}
it is stored in config.json file and passed as an argument to the k6.js.
I'm getting 
WARN[0000] `stages` was explicitly set to an empty value, running the script with 1 iteration in 1 VU
If I set normalDistributionStages in the k6.js then not problems, the test is working as expected performing normal distribution load, but I need it in external config.

Any help is greatly appreciated. 
Thanks

**Comment by mstoykov** [comment]
Hi @vladSeeq,

`normalDistributionStages` is a funciton and as such needs to be called. You can't call functions in config.json file as it is a JSON.

One workaround is to not use `config.json` at all and instead roll your own `config.js` which then is used to set `options` in the main script.

Please if you have usage questions use the [community forum](https://community.grafana.com/c/grafana-k6/70).

 I will close this as this is definitely nto jslib problem
